# Site settings
title: 侯振永的技术博客
email: 33273181@qq.com
description: 山高月小，水落石出
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/zhenyonghou" # the base hostname & protocol for your site
twitter_username: zhenyonghou
github_username:  zhenyonghou

# Build settings
markdown: kramdown
